### ISSUE TITLE
Support for field type "composite"

### ISSUE THREAD

**Issue by ranjjose-chaz** [pulkitbjri/HubblerTask#1]
The composite field should be **displayed fullscreen** (like how the add report page is shown). A composite field can have **any other field including another composite field**. Ideally, the implementation should be such that it works to **nth level**
 
Sample input JSON:
```

[{
		"field-name": "name",
		"type": "text",
		"required": true
	},
	{
		"field-name": "Zone",
		"type": "dropdown",
		"options": ["A", "B", "C", "D"]
	},
	{
		"field-name": "age",
		"type": "number"
	},
	{
		"field-name": "address",
		"type": "composite",
		"fields": [{
				"field-name": "Address line1",
				"type": "text",
				"required": true
			},
			{
				"field-name": "Address line2",
				"type": "text"
			},
			{
				"field-name": "City",
				"type": "text",
				"required": true
			},
			{
				"field-name": "State",
				"type": "text",
				"required": true
			}

		],
		"required": false
	}
]
```

**Comment by pulkitbjri** [comment]
I have completed the task.

Thanks

**Comment by ranjjose-chaz** [comment]
This isn't implemented

**Comment by ranjjose-chaz** [comment]
If you use exact same json as input, the app is crashing. Looks like you haven't checked in changes in the java file

**Comment by pulkitbjri** [comment]
Hi sir , it is working fine for me Here is the apk generated after pulling from this repo only 

[app-debug.zip](https://github.com/pulkitbjri/HubblerTask/files/2734092/app-debug.zip)

**Comment by ranjjose-chaz** [comment]
Yes. My comment was before you checked in all the files. However, after adding a composite field, the composite field data isn't persisted in the fields. That means when you open the composite field, the data isn't shown there.

**Comment by pulkitbjri** [comment]
Actually i haven't implemented that feature. I an adding this feature and will update it in the repo by tomorrow morning.

**Comment by pulkitbjri** [comment]
Added persisted composite fields
